version: "3.7"

services:
  web:
    image: getumbrel/node_warden:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3002:3002

    environment:
    # Bitcoin Core connection details
    BITCOIN_NETWORK: $BITCOIN_NETWORK
    BITCOIN_IP: $BITCOIN_IP
    BTCEXP_BITCOIND_PORT: $BITCOIN_RPC_PORT
    BTCEXP_BITCOIND_USER: $BITCOIN_RPC_USER
    BTCEXP_BITCOIND_PASS: $BITCOIN_RPC_PASS
    BITCOIN_P2P_PORT: $BITCOIN_P2P_PORT
    BITCOIN_RPC_PORT: $BITCOIN_RPC_PORT
    BITCOIN_RPC_AUTH: $BITCOIN_RPC_AUTH

    # LND environment variables
    LND_IP: $LND_IP
    LND_GRPC_PORT: $LND_GRPC_PORT
    LND_REST_PORT: $LND_REST_PORT

    # Tor proxy environment variables
    TOR_PROXY_IP: $TOR_PROXY_IP
    TOR_PROXY_PORT: $TOR_PROXY_PORT
